Continueloginmstests
McFluffen/TSFN-14 pull request #8
Opened 2024-03-07 14:17 UTC by simondereuver

Added some basic unit-tests for our inputValidation files. Also scrapped some of the old code and gave up on the idea to mock rabbitmq stuff. Approve if you think it looks good.

2024-03-07 17:18 UTC, Pramell94 requested changes
Looks good just delete that random rackage-lock.json file and we good :)

2024-03-07 17:18 UTC, Pramell94 commented on package-lock.json
Dont want this shit file please

2024-03-08 11:55 UTC, simondereuver commented on package-lock.json
Deleted rackage-lock.json file, pls review agane, ty

2024-03-08 12:06 UTC, Pramell94 approved these changes
lgtm 👍

2024-03-08 12:08 UTC, merged